apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: bench
data:
  nginx.conf: |
    server {
        listen INVALID_PORT;
        server_name localhost;
        location / {
            return 200 'ok\n';
            add_header Content-Type text/plain;
        }
    }
