config:
  tracing:
    otlpEndpoint: http://otel-collector:4317
    randomSampling: true
binds:
  - port: 3000
    listeners:
      - routes:
          - policies:
              cors:
                allowOrigins:
                  - "*"
                allowHeaders:
                  - "*"
                exposeHeaders:
                  - "Mcp-Session-Id"
            backends:
              - mcp:
                  targets:
                    - name: demo
                      mcp:
                        host: http://mcp-backend:3005/mcp
